apiVersion: v2
name: text-generation-inference
description: |
  A Helm chart for deploying HuggingFace text-generation-inference.
  Text Generation Inference (TGI) is a toolkit for deploying and serving
  Large Language Models (LLMs). TGI enables high-performance text
  generation for the most popular open-source LLMs.

type: application

version: 0.1.1

appVersion: "1.1.0"
