apiVersion: v2
name: stapi
description: |
  A Helm chart for deploying STAPI, an OpenAI compatible Embedding API using Sentence Transformers.

type: application

version: 0.1.2

appVersion: "v2.2.2-3"
