{{- if .Values.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lingo.roleBindingName" . }}
  labels:
    {{- include "lingo.labels" . | nindent 4 }}
  {{- with .Values.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

subjects:
- kind: ServiceAccount
  name: {{ include "lingo.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "lingo.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}