{{- if .Values.readManyPVC.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm.readManyPVCName" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  {{- if .Values.readManyPVC.sourcePVC }}
  dataSource:
    name: {{ .Values.readManyPVC.sourcePVC }}
    kind: {{ .Values.readManyPVC.sourceKind }}
    apiGroup: {{ .Values.readManyPVC.sourceAPIGroup }}
  {{- end }}
  accessModes:
  {{ toYaml .Values.readManyPVC.accessModes | nindent 2 }}
  {{- if .Values.readManyPVC.storageClass }}
  storageClassName: {{ .Values.readManyPVC.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.readManyPVC.size }}
{{- end }}
